apiVersion: v1
kind: Secret
metadata:
  name: ycrash-agent-config
stringData:
  config.yaml: |
    version: "1"
    options:
      k: {{ .Values.buggyapp.secrets.agentConfig.key }}
      s: {{ .Values.buggyapp.secrets.agentConfig.server }}
      port: 8085
      address: 0.0.0.0

