apiVersion: v1
kind: Secret
metadata:
  name: ycrash-agent-config
stringData:
  config.yaml: |
{{- if .Values.buggyapp.secrets.agentConfig }}
{{ toYaml .Values.buggyapp.secrets.agentConfig | indent 4 }}
{{- end }}
