apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: buggyapp
  name: buggyapp
spec:
  ports:
  - port: 9010
    protocol: TCP
    targetPort: 9010
  selector:
    app.kubernetes.io/name: buggyapp
