{{ if .Values.ycrash.secrets.license.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ycrash.secrets.license.name }}
stringData:
  license.lic: |
{{ .Values.ycrash.secrets.license.content | indent 4 }}
{{ end }}