{{ if and .Values.ycrash.storage }}
{{ if and .Values.ycrash.storage.s3 }}
apiVersion: v1
kind: Secret
metadata:
  name: ycrash-storage-s3
stringData:
  storage.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
    <properties>
      <comment>Storage Configurations</comment>	
      <entry key="s3.endPointURL">{{ .Values.ycrash.storage.s3.endPointUrl }}</entry>
      <entry key="s3.region">{{ .Values.ycrash.storage.s3.region }}</entry>
      <entry key="s3.bucketName">{{ .Values.ycrash.storage.s3.bucketName }}</entry>
      <entry key="s3.accessKey">{{ .Values.ycrash.storage.s3.accessKey }}</entry>
      <entry key="s3.secretKey">{{ .Values.ycrash.storage.s3.secretKey }}</entry>
    </properties>
{{ end }}
{{ end }}