apiVersion: v1
kind: Service
metadata:
  labels:
    app: ycrash
  name: ycrash
{{- if .Values.ycrash.service.extraAnnotations }}
  annotations:
{{ toYaml .Values.ycrash.service.extraAnnotations | indent 4 }}
{{- end }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ycrash
