ycrash:
  deployment:
    extraAnnotations:
    image: ycrash/ycrash:2.20.4.1
    imagePullPolicy: IfNotPresent
    replicas: 1
    resources:
      requests:
        cpu: 100m
        # You want to allocate 2x the size of your application's JVM heap size (i.e. -Xmx).
        # Let's say you want to monitor multiple applications whose heap size (i.e. -Xmx) varies,
        # then you want to pick the largest heap size.
        # Let's say your largest application's heap size is 2GB, then you want to allocate 4GB
        # as the RAM size requirement for yCrash server.
        memory: 3Gi
      limits:
        cpu: 
        memory: 
    secrets:
      license:
        secretName: ycrash-license
        key: license.lic
  secrets:
    license:
      create: true
      name: ycrash-license
      # content is to be set from --set-file ycrash.secrets.license.content=license.lic
      # the license.lic is obtained from https://ycrash.io/
      content:
  service:
    extraAnnotations:
  # If you would like to have high availability setup (multiple replicas), you would need to enable
  # a shared storage so that multiple replicas can access the same uploaded artifacts.
  storage:
    # Uncomment the following key to enable s3 storage: https://docs.ycrash.io/ycrash-server/administration/aws-s3-storage.html
    # s3:
      # endPointUrl: https://s3.us-west-1.amazonaws.com
      # region: us-west-1
      # bucketName: my-bucket
      # accessKey: my-access-key
      # secretKey: my-secrete-key
